[build]
# target = "avr-specs/avr-atmega2560.json"
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
# runner = "ravedude mega2560 -cb 57600"
runner = "ravedude uno -cb 57600"

[unstable]
build-std = ["core"]
